/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './router/routes/__root'
import { Route as AppImport } from './router/routes/_app'
import { Route as AppIndexImport } from './router/routes/_app/index'
import { Route as AppRecipesIndexImport } from './router/routes/_app/recipes/index'
import { Route as AppIngredientsIndexImport } from './router/routes/_app/ingredients/index'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppRecipesIndexRoute = AppRecipesIndexImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)

const AppIngredientsIndexRoute = AppIngredientsIndexImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/ingredients/': {
      id: '/_app/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AppIngredientsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppIngredientsIndexRoute: typeof AppIngredientsIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppIngredientsIndexRoute: AppIngredientsIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof AppIndexRoute
  '/ingredients': typeof AppIngredientsIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/ingredients': typeof AppIngredientsIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/ingredients/': typeof AppIngredientsIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/ingredients' | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ingredients' | '/recipes'
  id: '__root__' | '/_app' | '/_app/' | '/_app/ingredients/' | '/_app/recipes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/ingredients/",
        "/_app/recipes/"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/ingredients/": {
      "filePath": "_app/ingredients/index.tsx",
      "parent": "/_app"
    },
    "/_app/recipes/": {
      "filePath": "_app/recipes/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
